### ISSUE TITLE
Site Logo

### ISSUE THREAD

**Issue by richardshaju** [chethaslp/eventsatucek#10]
@chethaslp **If you have any other please share.**

![Screenshot 2024-04-12 214707](https://github.com/chethaslp/eventsatucek/assets/108459152/d41913f3-c571-4833-9140-c21a8c8b363c)
![Screenshot 2024-04-12 214749](https://github.com/chethaslp/eventsatucek/assets/108459152/9259458c-f398-44e9-ba7f-bd7af9691d82)
![Screenshot 2024-04-12 214835](https://github.com/chethaslp/eventsatucek/assets/108459152/88f17917-87d1-4654-bebe-23971b98f608)
![Screenshot 2024-04-12 215155](https://github.com/chethaslp/eventsatucek/assets/108459152/4e86c0a3-9291-4cfa-8696-29fc6638207e)

**Comment by chethaslp** [comment]
Site logo is under process of creation by IEEE SB UCEK's Creative Team. Let's wait for their inputs.
