### ISSUE TITLE
BUG: Notification allowing request 

### ISSUE THREAD

**Issue by richardshaju** [chethaslp/eventsatucek#23]
### Showing this on every vist in PWA

![Screenshot_2024-04-28-12-36-19-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/chethaslp/eventsatucek/assets/108459152/526bfe5b-b0cc-4b29-bf40-9cfb016dc916)

**Comment by chethaslp** [comment]
Fixed
