### ISSUE TITLE
Need Logos of different club

### ISSUE THREAD

**Issue by richardshaju** [chethaslp/eventsatucek#3]
- [x] Google Developers Student Club - UCEK
- [x] IEEE - UCEK
- [x] Legacy IEDC - UCEK
- [x] μlearn - UCEK
- [x] FOSS - UCEK
- [x] TinkerHub - UCEK
- [x] SFI UCEK
- [x] Meluhans Dance Club
- [x] Music Club - UCEK
- [x] Film Club - UCEK

**Comment by chethaslp** [comment]
Create a placeholder for music club and film club.
